#!/bin/bash

# getting latest version
version=$(curl -s https://api.github.com/repos/theryangeary/choose/releases/latest | jq -r .tag_name)

echo "🚀 Installing choose $version"

sudo curl -sLo /usr/bin/choose "https://github.com/theryangeary/choose/releases/latest/download/choose-x86_64-unknown-linux-musl"

sudo chmod +x /usr/bin/choose
