#!/bin/bash

# getting latest version
version=$(curl -s https://api.github.com/repos/sharkdp/hyperfine/releases/latest | jq -r .tag_name)

echo "Installing hyperfine $version"

curl -sLo - "https://github.com/sharkdp/hyperfine/releases/latest/download/hyperfine-${version}-x86_64-unknown-linux-musl.tar.gz" |
    sudo tar -xzC /usr/bin
