#!/bin/bash

curl -Lo - https://github.com/eza-community/eza/releases/download/v0.20.24/eza_x86_64-unknown-linux-musl.tar.gz | \
    tar -xzC $HOME/.local/bin # --transform='s|eza|ls|'

# echo 'alias ls="eza --color=auto --git --icons"' >> $ZSH_CUSTOM/aliases.zsh