#!/bin/bash

echo "🚀 Installing diffstatic (dift) latest"

curl -sLo - https://github.com/Wilfred/difftastic/releases/latest/download/difft-x86_64-unknown-linux-musl.tar.gz |
  sudo tar -xzC /usr/bin # --transform='s|eza|ls|'
