#!/bin/bash

# getting latest version
version=$(curl -s https://api.github.com/repos/mvdan/sh/releases/latest | jq -r .tag_name)

echo "Installing shfmt $version"

sudo curl -sLo /usr/bin/shfmt https://github.com/mvdan/sh/releases/download/latest/shfmt_${version}_linux_amd64

sudo chmod +x /usr/bin/shfmt
