#!/bin/bash

# getting latest version
version=$(curl -s https://api.github.com/repos/sharkdp/bat/releases/latest | jq -r .tag_name)

echo "🚀 Installing bat $version"

curl -sLo - "https://github.com/sharkdp/bat/releases/latest/download/bat-${version}-x86_64-unknown-linux-musl.tar.gz" |
  sudo tar -xzC /usr/bin
