#!/bin/bash

f="$ZEN/internal/completions/"

# getting latest version of fd
version=$(curl -s https://api.github.com/repos/sharkdp/fd/releases/latest | jq -r .tag_name)

echo "🚀 Installing fd $version"

curl -sLo - https://github.com/sharkdp/fd/releases/latest/download/fd-$version-x86_64-unknown-linux-musl.tar.gz |
  tar -xzC /tmp

sudo mv /tmp/fd-$version-x86_64-unknown-linux-musl/fd /usr/bin

mv /tmp/fd-$version-x86_64-unknown-linux-musl/autocomplete/_fd $f

rm -rfd /tmp/fd-$version-x86_64-unknown-linux-musl
# sudo rm /usr/bin/asdf
