#!/usr/bin/env bash

local file=gh_2.69.deb
pushd $(pwd)
cd /tmp
curl -Lo $file https://github.com/cli/cli/releases/download/v2.69.0/gh_2.69.0_linux_amd64.deb
sudo apt install "./$file"
popd

gh auth login

gh extension install github/gh-copilot

gh copilot auth login
