#!/usr/bin/env python3

# O shebang acima instrui o sistema a usar o Python 3.
# O comando env localiza o interpretador no ambiente atual(útil para venv, pyenv, etc).

import datetime

# Obtém a data e hora atual em UTC
now = datetime.datetime.now(datetime.timezone.utc)

# Formata para ISO 8601 com o sufixo 'Z'(Zulu / UTC)
print(now.isoformat(timespec = 'milliseconds').replace('+00:00', 'Z'))
