FROM debian:trixie

RUN apt update && apt install -y \
    sudo \
    git \
    binutils \
    gdb \
    strace \
    lsof \
    file \
    curl \
    systemd \
    libpam-systemd \
    pipewire-audio-client-libraries

RUN rm -rf /var/lib/apt/lists/*
