# syntax=docker/dockerfile:1

FROM python:slim-trixie

# Tools available via apt
RUN apt update && apt install -y \
    bat \
    btop \
    fd-find \
    fzf \
    ripgrep \
    lazygit \
    meld \
    neovim \
    kitty \
    procs \
    hyperfine \
    sqlite3 \
    zsh \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root

CMD ["/bin/zsh"]
